---
title: "R Notebook"
output: html_notebook
---


##Import

```{r}
library(tidyverse)

#gdp.df <- readr::read_csv("./GDP.csv")

pop.df <- readr::read_csv("./POP3.csv")
gdp.df <- readr::read_csv("./GDP2.csv")
prod.df <- readr::read_csv("./AgPro.csv")
```


##Rename Columns

```{r}

colnames(pop.df)
pop.df = pop.df %>% rename(Country.Code = `Country Code`)
pop.df = pop.df %>% rename(Country.Name = `Country Name`)


#colnames(gdp.df) = paste('g', colnames(gdp.df), sep="")
gdp.df = gdp.df %>% rename(Country.Code = `Country Code`)
gdp.df = gdp.df %>% rename(Country.Name = `Country Name`)

head(prod.df)
prod.df = prod.df %>% rename(Country.Code = `Area Abbreviation`)
prod.df = prod.df %>% rename(Country.Name = `Area`)


gdp.df = gdp.df %>% select(-`Indicator Name`, -`Indicator Code`)
pop.df = pop.df %>% select(-`Indicator Name`, -`Indicator Code`)




```


##GATHER
```{r}

gdpgath = gdp.df %>% gather(key='year', value='GDP', '1983':'2013', na.rm=TRUE)
gdpgath = gdpgath %>% select(., -('1960':'2019'))

popgath = pop.df %>% gather(key='year', value='Population', '1983':'2013', na.rm=TRUE)
popgath = popgath %>% select(., -('1960':'2019'))

prodgath = prod.df %>% gather(key='year', value='prod', 'Y1983':'Y2013', na.rm=TRUE)
prodgath = prodgath %>% select(., -('Y1961':'Y1982'))


#get y axis out of scinot, interval x axis
popgath %>% filter(Country.Name=='Afghanistan') %>%
  ggplot(., aes(x=year, ymax=GDP, ymin=0)) +
  geom_linerange(color='red4', size=0.9)




prodgath %>% group_by(Item) %>%
  summarise(sum=sum(prod)) %>%
  arrange(desc(sum)) 

popgath %>%  filter(year=='2013') %>%
  arrange(desc(Population)) %>%
  top_n(100)



#get the y's out of year in prodgath


prodgath = prodgath %>% mutate(., year = (gsub('Y', "", prodgath$year)))



```




```{r}
prodgath %>% filter(., Country.Name=='United States')
prodgath %>% filter(., Country.Name=='United States of America')
```




##Merge

```{r}
prodgath = prodgath %>% mutate(., Country.Name = (gsub('China, mainland', "China", prodgath$Country.Name)))
prodgath = prodgath %>% mutate(., Country.Name = (gsub('China, Taiwan Province of', "China", prodgath$Country.Name)))
prodgath = prodgath %>% mutate(., Country.Name = (gsub('China, Hong Kong SAR', "China", prodgath$Country.Name)))
prodgath = prodgath %>% mutate(., Country.Name = (gsub('Macao SA', "China", prodgath$Country.Name)))
prodgath = prodgath %>% mutate(., Country.Name = (gsub('United States of America', 'United States', prodgath$Country.Name)))


merge1 = inner_join(prodgath, popgath, by=c("Country.Name", "Country.Code", "year"))

merge2 = inner_join(merge1, gdpgath, by=c("Country.Name", "Country.Code", "year"))

zb.df <- readr::read_csv("./zabclean.csv")
zb.df = zb.df %>% rename(Country.Name = 'Country')
zb.dfu = zb.df %>% unique()

merge3 = inner_join(merge2, zb.dfu, by="Country.Name")



topitems = merge3 %>% filter(year=='2013') %>%
  group_by(Item) %>%
  summarise(sum=sum(prod)) %>%
  arrange(desc(sum)) %>%
  top_n(40)

topitemitem = topitems %>% select(., Item)
topitemitem

merge4 = inner_join(merge3, topitemitem, by="Item")

merge4$GDP = merge4$GDP/1000000000
merge4$Population = merge4$Population/1000000
merge4$GDPperCap = (merge4$GDP*1000000000)/(merge4$Population*1000000)



unique(merge4$Country.Name)
unique(merge4$Income.Group)



merge4 %>% filter(year=='2013') %>%
  group_by(Income.Group) %>% 
  summarise(sum=sum(prod))



merge4 %>% filter(., Country.Name=='United States')



merge4 %>% filter(Country.Name=='Japan' & year=='2013') %>%
  group_by(Item)

  # ggplot(aes(x=Item, y=prod))+
  # geom_bar(aes(fill=Element), stat='identity', position='dodge')



#year vs gdp per capita
merge4 %>% filter(Country.Name=='Algeria') %>%
  group_by(year) %>%
  summarise(GDPcap = mean(GDPperCap)) %>%
  ggplot(., aes(x=year, ymax=GDPcap, ymin=0)) +
  geom_linerange(color='red4', size=0.9) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


#top 5 produce by year

merge4 %>% filter(Country.Name=='China' & year=='2000') %>%
  group_by(Item) %>%
  summarise(outp = sum(prod)) %>%
  arrange(desc(outp)) %>%
  top_n(5) %>% 
  ggplot() +
  geom_bar(aes(x=reorder(Item, -outp),y=outp), stat='identity') +
  theme(axis.text.x=element_text(angle=45, hjust=1))



#types of produce toggle
merge4 %>% filter(Country.Name=='Algeria' & Item=='Barley and products') %>%
  group_by(year) %>%
  summarise(outp = sum(prod)) %>%
  ggplot(., aes(x=year, ymax=outp, ymin=0)) +
  geom_linerange(color='red4', size=0.9)




##this is my scatter boy
merge4 %>% filter(year=='2013' & Element=='Food') %>%
  group_by(Country.Name) %>%
  summarise(output=sum(prod), GDP=mean(GDP)) %>%
  ggplot(aes(x=output, y=GDP, label=Country.Name)) +
  geom_point() + 
  ggtitle('Total Output vs. GDP') +
  ylab('GDP ($bn)') +
  xlab('Output (1000 tonnes)')

merge4 %>% filter(year=='2013' & Element=='Food') %>%
  group_by(Country.Name) %>%
  summarise(output=sum(prod), popu=mean(Population)) %>%
  ggplot(aes(x=output, y=popu, label=Country.Name)) +
  geom_point() + 
  ggtitle('Total Output vs. Population') +
  ylab('Population (millions)') +
  xlab('Output (1000 tonnes)')+
  geom_smooth(method = "lm")



merge4 %>% filter(year=='2013' & Element=='Food') %>%
  group_by(Country.Name) %>%
  summarise(output=sum(prod), gdppc=mean(GDPperCap)) %>%
  ggplot(aes(x=output, y=gdppc, label=Country.Name)) +
  geom_point() + 
  ggtitle('Total Output vs. GDPPC') +
  ylab('GDPPC ($)') +
  xlab('Output (1000 tonnes)') +
  geom_smooth(method = "lm")




mapdata = merge4  %>%
  group_by(Country.Name, Country.Code, year) %>%
  summarise(tot=sum(prod))

mapdata

yoy = merge4 %>% filter((year=='2013'|year=='2012') & Element=='Food') %>%
  group_by(Country.Name, year) %>%
  summarise(output=sum(prod), gdppc=mean(GDPperCap)) 

merge4 %>% filter((year=='2013'|year=='2012') & Element=='Food') %>%
  group_by(Country.Name, year) %>%
  summarise(output=sum(prod), gdppc=mean(GDPperCap)) %>%
  group_by(Country.Name) %>%
  summarise(outyy=(output[year=='2013']-output[year=='2012'])/output[year=='2012'], 
            gdppcyy=(gdppc[year=='2013']-gdppc[year=='2012'])/gdppc[year=='2012']) %>%
  ggplot(aes(x=outyy, y=gdppcyy, label=Country.Name)) +
  geom_point() + 
  ggtitle('YoY Output Growth vs. YoY GDPPC Growth') +
  ylab('YoY GDPPC Growth (%)') +
  xlab('YoY Output Growth (%)') +
  geom_smooth(method = "lm")

merge4 %>% filter(Income.Group=='Lower middle income' & (year=='2013'|year=='2012') & Element=='Food') %>%
  group_by(Country.Name, year) %>%
  summarise(output=sum(prod), gdppc=mean(GDPperCap)) %>%
  group_by(Country.Name) %>%
  summarise(outyy=(output[year=='2013']-output[year=='2012'])/output[year=='2012'], 
            gdppcyy=(gdppc[year=='2013']-gdppc[year=='2012'])/gdppc[year=='2012']) %>%
  ggplot(aes(x=outyy, y=gdppcyy, label=Country.Name)) +
  geom_point() + 
  ggtitle('YoY Output Growth vs. YoY GDPPC Growth') +
  ylab('YoY GDPPC Growth (%)') +
  xlab('YoY Output Growth (%)') +
  geom_smooth(method = "lm")


merge4 %>% filter(Region=='Sub-Saharan Africa' & (year=='2013'|year=='2012') & Element=='Food') %>%
  group_by(Country.Name, year) %>%
  summarise(output=sum(prod), gdppc=mean(GDPperCap)) %>%
  group_by(Country.Name) %>%
  summarise(outyy=(output[year=='2013']-output[year=='2012'])/output[year=='2012'], 
            gdppcyy=(gdppc[year=='2013']-gdppc[year=='2012'])/gdppc[year=='2012']) %>%
  ggplot(aes(x=outyy, y=gdppcyy, label=Country.Name)) +
  geom_point() + 
  ggtitle('YoY Output Growth vs. YoY GDPPC Growth') +
  ylab('YoY GDPPC Growth (%)') +
  xlab('YoY Output Growth (%)') +
  geom_smooth(method = "lm")



write.csv(merge4, "./merge4.csv", row.names = FALSE)

as.character(merge4$year)



```











